theme = "tokyonight"

[editor]
line-number="relative"
color-modes=true

[editor.cursor-shape]
insert="bar"

[editor.auto-save]
focus-lost=true

[editor.statusline]
left = ["mode", "spinner"]
center = []
right = ["diagnostics", "file-name", "selections", "position",   "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.file-picker]
hidden = false

[keys.normal]
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
space.e = [
  ':sh rm -f /tmp/yazi-path',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-path',
  ":open %sh{cat /tmp/yazi-path}",
  ":redraw",
  ":reload-all",
  ':set mouse false',
  ':set mouse true'
]

[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]

